### ISSUE TITLE
Nouvelle documentation pico-8

### ISSUE THREAD

**Issue by merwok** [gamedevalliance/fairedesjeux.fr#43]
zep a remplacé le manuel textuel par une page HTML plus sympa: https://www.lexaloffle.com/dl/docs/pico-8_manual.html
Les ancres ont changé, il faudrait adapter les liens comme par exemple celui pour les bitwise ops en fin de page https://fairedesjeux.fr/pico-8/techniques-avancees/manipuler-la-memoire/

**Comment by aureliendossantos** [comment]
Merci pour l'info, je change ça très vite !
